
## Macros

CC = g++ -std=c++11
SRCMAX = src/maxmin.cpp
SRCMODA = src/moda.cpp
OBJ = obj/maxmin.o obj/moda.o
DESTMAX = bin/maxmin
DESTMODA = bin/moda	
INCLUDE = -Iinclude


maxmin:
	$(CC) -o $(DESTMAX) $(SRCMAX) $(INCLUDE)


moda:
	$(CC) -o $(DESTMODA) $(SRCMODA) $(INCLUDE) 
