/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

/**
 *
 * @author Jorge
 */
public class VistaJugador extends javax.swing.JPanel {

    /**
     * Creates new form VistaJugador
     */
    public VistaJugador() {
        initComponents();
    }

    public void actualizar(String descripcionJugador){
        this.jtTextoJugador.setText(descripcionJugador);
        this.repaint();
        this.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTextoJugador = new javax.swing.JTextArea();
        labelJugador = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 63, 63), 10, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtTextoJugador.setEditable(false);
        jtTextoJugador.setColumns(20);
        jtTextoJugador.setRows(5);
        jScrollPane1.setViewportView(jtTextoJugador);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 410, 490));

        labelJugador.setFont(new java.awt.Font("Sylfaen", 0, 22)); // NOI18N
        labelJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJugador.setText("Jugador");
        labelJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, new java.awt.Color(102, 0, 0)));
        add(labelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 119, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtTextoJugador;
    private javax.swing.JLabel labelJugador;
    // End of variables declaration//GEN-END:variables
}
